### ISSUE TITLE
Migration of MCM from in-tree to OOT for Openstack

### ISSUE THREAD

**Issue by dkistner** [gardener/machine-controller-manager-provider-openstack#1]
**What would you like to be added**:
To proceed with the mcm out of tree implementation story we need to add an OpenStack provider.
This is to track the progress.

Points to cover

- [x] Develop the MCM OpenStack OOT code
- [x] Develop a test framework to allow testing
- [x] Write unit tests to cover the edge cases
- [x] Integrate the changes with gardener/extension-openstack

Aligning with https://github.com/gardener/machine-controller-manager-provider-azure/issues/11

**Comment by prashanth26** [comment]
Close in favor of - gardener/gardener-extension-provider-openstack#224.
