### ISSUE TITLE
Patch server ports when adopting machines

### ISSUE THREAD

**Issue by timuthy** [gardener/machine-controller-manager-provider-openstack#23]
**What happened**:
When MCM crashes during a machine creation, it'll adopt the already created machine during the next reconciliation but it doesn't finish the creation as it would have done w/o crashing. Concretely, patching the server ports (see [here](https://github.com/gardener/machine-controller-manager-provider-openstack/blob/f404a03e966aba096ed80ca94cac1a91a7ce80d8/pkg/driver/executor/executor.go#L86)) is silently skipped.

**What you expected to happen**:
The result of a machine creation should be the same, no matter if MCM crashes or not.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run MCM
2. Create a `Machine`
3. Stop MCM right after it has created the machine in OpenStack
4. Start MCM again
5. Wait until machine adoption
6. Check port configuration belonging to the created machine, it has no `allowed_address_pairs`.

**Comment by prashanth26** [comment]
This issue is now fixed with [this PR](https://github.com/gardener/machine-controller-manager-provider-openstack/pull/22) right?

**Comment by timuthy** [comment]
> This issue is now fixed with [this PR](https://github.com/gardener/machine-controller-manager-provider-openstack/pull/22) right?

I don't think so 👀
