### ISSUE TITLE
Are we propagating Worker Group Names to the Driver?

### ISSUE THREAD

**Issue by afritzler** [gardener/machine-controller-manager-provider-openstack#29]
I am currently looking into implementing the hypervisor anti-affinity for OpenStack. Since we are only having IaaS specific coding in the machine driver, I currently don't have any logical grouping possibility on the driver level (which is necessary for creating/updating a server group on the infrastructure level).

One idea could be to propagate the worker group name down to the `MachineClassSpec`. Not sure if that is a good idea. WDYT?

**Comment by dkistner** [comment]
This is meanwhile implemented. 
So it is possible to define in the machineclass a servergroup where the machines should be assigned to.
/close
